# This file is auto-generated by CI on each release.
# To use: brew tap portless-rs/portless https://github.com/portless-rs/portless && brew install portless
class Portless < Formula
  desc "Replace port numbers with stable .localhost URLs for local development"
  homepage "https://github.com/portless-rs/portless"
  version "PLACEHOLDER_VERSION"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "PLACEHOLDER_BASE_URL/portless-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_ARM64_SHA256"
    else
      url "PLACEHOLDER_BASE_URL/portless-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_X86_64_SHA256"
    end
  end

  def install
    bin.install "portless"
  end

  test do
    assert_match "portless", shell_output("#{bin}/portless --help")
  end
end
