# This file is auto-generated by CI on each release.
# To use: brew tap lusons/portless && brew install portless
class Portless < Formula
  desc "Replace port numbers with stable .localhost URLs for local development"
  homepage "https://github.com/lusons/portless-rs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lusons/portless-rs/releases/download/v0.1.0/portless-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_ARM64_SHA256"
    else
      url "https://github.com/lusons/portless-rs/releases/download/v0.1.0/portless-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_X86_64_SHA256"
    end
  end

  def install
    bin.install "portless"
  end

  test do
    assert_match "portless", shell_output("#{bin}/portless --help")
  end
end
